version: '3'
services: 
    mongo:
        restart: always
        image: 'mongo:latest'
    redis:
        restart: always
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules 
            - ./server:/app
        environment: 
            - NODE_ENV=development
        depends_on:
            - mongo
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app

