version: 2.1
jobs:
    build:
        machine: true
        steps:
            - checkout
            - save_cache:
                paths:
                - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: docker build -t hayreddintuzel/pathinker-client-test -f ./client/Dockerfile.dev ./client
            - run: docker build -t hayreddintuzel/pathinker-server-test -f ./server/Dockerfile.dev ./server
            - run: docker build -t hayreddintuzel/pathinker-worker-test -f ./worker/Dockerfile.dev ./worker
            - run: docker run -e CI=true hayreddintuzel/pathinker-client-test npm test
            - run: docker run -e CI=true hayreddintuzel/pathinker-server-test npm test
            - run: docker run -e CI=true hayreddintuzel/pathinker-worker-test npm test
